services:
  container-kingdom:
    container_name: container-kingdom
    build: ./compose
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./compose/nginx.conf:/etc/nginx/conf.d/default.conf
      - "./src:/var/www/html"
    networks:
      - docker-api

  docker-api:
    image: tecnativa/docker-socket-proxy
    container_name: docker-api
    restart: always
    ports:
      - "2375:2375"

    environment:

      POST: 1

      CONTAINERS: 1

      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTART: 1


      EXEC: ${CONTAINER_EXEC}
      BUILD: ${CONTAINER_BUILD}
      NETWORKS: ${CONTAINER_NETWORKS}
      SYSTEM: 1      # Autoriser la lecture des infos Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-api

networks:
  docker-api:
    name: docker-api
    driver: bridge


