services:
  container-kingdom:
    container_name: container-kingdom
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - "./src:/var/www/html"
      - "./src:/src"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.container-kingdom.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.container-kingdom.entrypoints=websecure"
      - "traefik.http.routers.container-kingdom.tls.certresolver=myresolver"
    networks:
      - web
      - docker-api

networks:
  web:
    name: web
    external: true
  docker-api:
    name: docker-api
    external: true

