services:
  container-kingdom:
    container_name: container-kingdom
    build: ./compose
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./compose/nginx.conf:/etc/nginx/conf.d/default.conf
      - "./src:/var/www/html"
    networks:
      - docker-api

  docker-api:
    image: tecnativa/docker-socket-proxy
    container_name: docker-api
    restart: always
    ports:
      # - "127.0.0.1:2375:2375"
      # TODO : Change this to a more secure setup
      # - "2375:2375"
      - "${LOCAL_IP}:2375:2375"

    environment:
      CONTAINERS: 1 # 🔥 Active l'accès aux containers
      EXEC: 0        # Empêcher l'exécution de commandes
      BUILD: 0       # Empêcher la construction d'images
      NETWORKS: 0    # Empêcher les modifications de réseaux
      SYSTEM: 1      # Autoriser la lecture des infos Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-api

networks:
  docker-api:
    name: docker-api
    driver: bridge


