services:
  container-kingdom:
    container_name: container-kingdom
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - "../src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.container-kingdom.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.container-kingdom.entrypoints=websecure"
      - "traefik.http.routers.container-kingdom.tls.certresolver=myresolver"
    networks:
      - web
      - docker-api

  docker-api:
    image: tecnativa/docker-socket-proxy
    container_name: docker-api
    ports:
      # - "127.0.0.1:2375:2375"
      # TODO : Change this to a more secure setup
      # - "2375:2375"
      - "${LOCAL_IP}:2375:2375"

    environment:
      CONTAINERS: 1 # 🔥 Active l'accès aux containers
      EXEC: 0        # Empêcher l'exécution de commandes
      BUILD: 0       # Empêcher la construction d'images
      NETWORKS: 0    # Empêcher les modifications de réseaux
      SYSTEM: 1      # Autoriser la lecture des infos Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-api

networks:
  web:
    name: web
    external: true
  docker-api:
    name: docker-api
    external: true

